---
default_desc: La guida completa ai pin GPIO del Raspberry Pi originale, del Modello
  B+ e del Raspberry Pi 2
default_title: Assegnazione pin GPIO del Raspberry Pi - Pi 1, B+, Pi 2
title_suffix: " - Assegnazione pin GPIO del Raspberry Pi"
base_url: /pinout/
resource_url: /resources/
domain: it.pinout.xyz
url_suffix:
urls:
  GND: massa
strings:
- made_by: 'Prodotto da {manufacturer}'
- type_hat: 'Fattore di forma HAT'
- type_phat: 'Fattore di forma pHAT'
- type_classic: 'Fattore di forma classico'
- pin_header: '{} pin header'
- uses_i2c: 'Utilizza I2C'
- uses_spi: 'Utilizza SPI'
- wiring_pi_pin: 'Wiring Pi pin {}'
- uses_n_gpio_pins: 'Utilizza {} GPIO pins'
- bcm_pin_rev1_pi: 'BCM pin {} su Raspberry Rev 1 (le prime edizioni)'
- physical_pin_n: 'Pin fisico {}'
- more_information: 'Maggiori informazioni'
- github_repository: 'GitHub Repository'
- buy_now: 'Acquista'
overlays:
- ground
- uart
- i2c
- spi
- arduino-spi
- wiringpi
- iqaudio-pi-dac
- display-o-tron
- display-o-tron-hat
- dots
- explorer-hat
- explorer-hat-pro
- piano-hat
- piborg-ledborg
- pibrella
- piglow
- rtk-000-001
- sense-hat
- skywriter-hat
- traffic-hat
- unicorn-hat
