---
default_desc: The comprehensive Raspberry Pi GPIO Pinout guide for the original Raspberry
  Pi, B+ and Pi 2
default_title: Raspberry Pi GPIO Pinout - Pi 1, B+, Pi 2
title_suffix: " at Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: de.pinout.xyz
url_suffix:
urls:
  GND: masse_ground
strings:
- made_by: '* Made by {manufacturer}'
- type_hat: '* HAT form-factor'
- type_classic: '* Classic form-factor'
- pin_header: '* {} pin header'
- uses_i2c: '* Uses I2C'
- wiring_pi_pin: 'Wiring Pi pin {}'
overlays:
- ground
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- display-o-tron-hat
- dots
- traffic-hat
- iqaudio-pi-dac
- piano-hat
- sense-hat
