---
default_desc: Le guide complet des broches GPIO de la Raspberry Pi
  Pi, B+ and Pi 2
default_title: Raspberry Pi GPIO Pinout - Pi 1, B+, Pi 2
title_suffix: " Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: fr.pinout.xyz
url_suffix:
urls:
  GND: ground
strings:
- made_by: '* Produit {manufacturer}'
- type_hat: '* format HAT'
- type_classic: '* format Classic'
- pin_header: '* {} broches'
- uses_i2c: '* bus I2C'
- wiring_pi_pin: 'Broche Wiring Pi {}'
overlays:
- ground
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- display-o-tron-hat
- dots
- traffic-hat
- iqaudio-pi-dac
- piano-hat
- sense-hat
